version: '3'
services:
  express:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  client:
    build:
      dockerfile: client.dockerfile
    ports:
      - "8080:8080"

  admin:
    build:
      dockerfile: admin.dockerfile
    ports:
      - "8081:8080"
